/*
 * Copyright 2023 Simon Emms <simon@simonemms.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: providers/v1/providers.proto

package basic

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to run command1
type Command1Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo target
	Input         string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command1Request) Reset() {
	*x = Command1Request{}
	mi := &file_providers_v1_providers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command1Request) ProtoMessage() {}

func (x *Command1Request) ProtoReflect() protoreflect.Message {
	mi := &file_providers_v1_providers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command1Request.ProtoReflect.Descriptor instead.
func (*Command1Request) Descriptor() ([]byte, []int) {
	return file_providers_v1_providers_proto_rawDescGZIP(), []int{0}
}

func (x *Command1Request) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// Response to a command1 request
type Command1Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image id - if not set then all other parameters are required
	Output        string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command1Response) Reset() {
	*x = Command1Response{}
	mi := &file_providers_v1_providers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command1Response) ProtoMessage() {}

func (x *Command1Response) ProtoReflect() protoreflect.Message {
	mi := &file_providers_v1_providers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command1Response.ProtoReflect.Descriptor instead.
func (*Command1Response) Descriptor() ([]byte, []int) {
	return file_providers_v1_providers_proto_rawDescGZIP(), []int{1}
}

func (x *Command1Response) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Request to run command2
type Command2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repo target
	Input1        string `protobuf:"bytes,1,opt,name=input1,proto3" json:"input1,omitempty"`
	Input2        string `protobuf:"bytes,2,opt,name=input2,proto3" json:"input2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command2Request) Reset() {
	*x = Command2Request{}
	mi := &file_providers_v1_providers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command2Request) ProtoMessage() {}

func (x *Command2Request) ProtoReflect() protoreflect.Message {
	mi := &file_providers_v1_providers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command2Request.ProtoReflect.Descriptor instead.
func (*Command2Request) Descriptor() ([]byte, []int) {
	return file_providers_v1_providers_proto_rawDescGZIP(), []int{2}
}

func (x *Command2Request) GetInput1() string {
	if x != nil {
		return x.Input1
	}
	return ""
}

func (x *Command2Request) GetInput2() string {
	if x != nil {
		return x.Input2
	}
	return ""
}

// Response to a command2 request
type Command2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image id - if not set then all other parameters are required
	Output1       string `protobuf:"bytes,1,opt,name=output1,proto3" json:"output1,omitempty"`
	Output2       string `protobuf:"bytes,2,opt,name=output2,proto3" json:"output2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command2Response) Reset() {
	*x = Command2Response{}
	mi := &file_providers_v1_providers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command2Response) ProtoMessage() {}

func (x *Command2Response) ProtoReflect() protoreflect.Message {
	mi := &file_providers_v1_providers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command2Response.ProtoReflect.Descriptor instead.
func (*Command2Response) Descriptor() ([]byte, []int) {
	return file_providers_v1_providers_proto_rawDescGZIP(), []int{3}
}

func (x *Command2Response) GetOutput1() string {
	if x != nil {
		return x.Output1
	}
	return ""
}

func (x *Command2Response) GetOutput2() string {
	if x != nil {
		return x.Output2
	}
	return ""
}

var File_providers_v1_providers_proto protoreflect.FileDescriptor

var file_providers_v1_providers_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x27, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x22, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x41, 0x0a,
	0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x32,
	0x22, 0x46, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x31, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x31, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x72, 0x73, 0x69, 0x6d, 0x6f, 0x6e, 0x65, 0x6d, 0x6d, 0x73, 0x2f, 0x67, 0x69,
	0x74, 0x62, 0x6f, 0x78, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_providers_v1_providers_proto_rawDescOnce sync.Once
	file_providers_v1_providers_proto_rawDescData []byte
)

func file_providers_v1_providers_proto_rawDescGZIP() []byte {
	file_providers_v1_providers_proto_rawDescOnce.Do(func() {
		file_providers_v1_providers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_providers_v1_providers_proto_rawDesc), len(file_providers_v1_providers_proto_rawDesc)))
	})
	return file_providers_v1_providers_proto_rawDescData
}

var (
	file_providers_v1_providers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
	file_providers_v1_providers_proto_goTypes  = []any{
		(*Command1Request)(nil),  // 0: basic.v1.Command1Request
		(*Command1Response)(nil), // 1: basic.v1.Command1Response
		(*Command2Request)(nil),  // 2: basic.v1.Command2Request
		(*Command2Response)(nil), // 3: basic.v1.Command2Response
	}
)

var file_providers_v1_providers_proto_depIdxs = []int32{
	0, // 0: basic.v1.BasicService.Command1:input_type -> basic.v1.Command1Request
	2, // 1: basic.v1.BasicService.Command2:input_type -> basic.v1.Command2Request
	1, // 2: basic.v1.BasicService.Command1:output_type -> basic.v1.Command1Response
	3, // 3: basic.v1.BasicService.Command2:output_type -> basic.v1.Command2Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_providers_v1_providers_proto_init() }
func file_providers_v1_providers_proto_init() {
	if File_providers_v1_providers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_providers_v1_providers_proto_rawDesc), len(file_providers_v1_providers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_providers_v1_providers_proto_goTypes,
		DependencyIndexes: file_providers_v1_providers_proto_depIdxs,
		MessageInfos:      file_providers_v1_providers_proto_msgTypes,
	}.Build()
	File_providers_v1_providers_proto = out.File
	file_providers_v1_providers_proto_goTypes = nil
	file_providers_v1_providers_proto_depIdxs = nil
}
